# Generated by Django 4.2.1 on 2023-07-13 17:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('medconnectMain', '0004_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter a valid WhatsApp phone number in the format +1234567890123', max_length=20, null=True, region=None),
        ),
    ]
