# Generated by Django 4.2.1 on 2023-06-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medconnectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
