# Generated by Django 4.2.1 on 2023-06-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnectApp', '0002_remove_user_address_remove_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
