# Generated by Django 4.2.1 on 2023-06-12 14:19

from django.db import migrations, models
import medconnectApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnectApp', '0007_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/person-01.jpg', upload_to=medconnectApp.models.User.image_upload_to),
        ),
    ]
