# Generated by Django 4.2.1 on 2023-07-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnectApp', '0009_alter_user_image_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text=None, max_length=255),
        ),
    ]
