# Generated by Django 4.2.1 on 2023-07-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnectApp', '0010_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', help_text=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
